apt-get install python
apt-get install nmap
apt-get install ruby
apt-get install php
apt-get install metasploit
pip install python-geoip-geolite2
pip install googlesearch-python
pip install pyshorteners
pip install dnspython
pip install requests
pip install hashlib
pip install secrets
pip install sockets
pip install scapy
pip install bs4
